### ISSUE TITLE
Login attempt fails, PTO panics

### ISSUE THREAD

**Issue by jfrederickson** [tdfischer/pto#45]
Matrix ID is @jon:terracrypt.net, client is Quassel, ident is "jon", server password is my password.

```
jonathan@alpha:~/sources/pto$ RUST_BACKTRACE=1 cargo run -- terracrypt.net 0.0.0.0:4242
     Running `target/debug/pto terracrypt.net 0.0.0.0:4242`
thread '<unnamed>' panicked at 'Could not login!: UrlNotFound', ../src/libcore/result.rs:760
stack backtrace:
   1:     0x562e8deda090 - sys::backtrace::tracing::imp::write::haa19c02b4de52f3bG0t
   2:     0x562e8dedc535 - panicking::log_panic::_<closure>::closure.41218
   3:     0x562e8dedbfb0 - panicking::log_panic::h527fe484e9de8fe1W7x
   4:     0x562e8decd453 - sys_common::unwind::begin_unwind_inner::h51f64b1a34c60827fTs
   5:     0x562e8decdb08 - sys_common::unwind::begin_unwind_fmt::h0845853a1913f45blSs
   6:     0x562e8ded96f1 - rust_begin_unwind
   7:     0x562e8df0898f - panicking::panic_fmt::h3967afc085fe8067LFK
   8:     0x562e8dd552a1 - result::_<impl>::expect::expect::h14909738735884939944
                        at ../src/libcore/macros.rs:29
   9:     0x562e8dd393af - bridge::_<impl>::handle_client::h4c3beb9fd3688262Dec
                        at src/bridge.rs:378
  10:     0x562e8dd38b82 - bridge::_<impl>::ready::hbc9d7d5120ba7167rKb
                        at src/bridge.rs:50
  11:     0x562e8dd47a13 - event_loop::_<impl>::io_event::io_event::h16631942979517961819
                        at /home/jonathan/.cargo/registry/src/github.com-88ac128001ac3a9a/mio-0.5.0/src/event_loop.rs:343
  12:     0x562e8dd47949 - event_loop::_<impl>::io_process::io_process::h3603654275074776935
                        at /home/jonathan/.cargo/registry/src/github.com-88ac128001ac3a9a/mio-0.5.0/src/event_loop.rs:335
  13:     0x562e8dd47180 - event_loop::_<impl>::run_once::run_once::h3489195311041105944
                        at /home/jonathan/.cargo/registry/src/github.com-88ac128001ac3a9a/mio-0.5.0/src/event_loop.rs:298
  14:     0x562e8dd46b0c - event_loop::_<impl>::run::run::h11559222182195999125
                        at /home/jonathan/.cargo/registry/src/github.com-88ac128001ac3a9a/mio-0.5.0/src/event_loop.rs:247
  15:     0x562e8dcf3956 - bridge::_<impl>::run::h450c39ab45a6496cW7b
                        at src/bridge.rs:276
  16:     0x562e8dcf3405 - _<impl>::ready::_<closure>::closure.14307
                        at src/main.rs:56
  17:     0x562e8dcf2e43 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.14260
                        at ../src/libstd/thread/mod.rs:274
  18:     0x562e8dcf2db8 - sys_common::unwind::try::try_fn::try_fn::h261978716724135801
                        at ../src/libstd/sys/common/unwind/mod.rs:163
  19:     0x562e8ded9538 - __rust_try
  20:     0x562e8ded648b - sys_common::unwind::try::inner_try::h771fec597ec8f35cNPs
  21:     0x562e8dcf2cf5 - sys_common::unwind::try::try::h16901009832689950734
                        at ../src/libstd/sys/common/unwind/mod.rs:133
  22:     0x562e8dcf2b3b - std::thread::_<impl>::spawn::_<closure>::closure.14235
                        at ../src/libstd/thread/mod.rs:274
  23:     0x562e8dcf3697 - boxed::_<impl>::call_box::call_box::h4900206345153519334
                        at ../src/liballoc/boxed.rs:541
  24:     0x562e8dedb083 - sys::thread::_<impl>::new::thread_start::haf749b76474da6b089w
  25:     0x7f3cc06af181 - start_thread                                                                                                                                       [6/468]
  26:     0x7f3cc0ec947c - __clone
  27:                0x0 - <unknown>
thread '<unnamed>' panicked at 'Could not login!: UrlNotFound', ../src/libcore/result.rs:760
stack backtrace:
   1:     0x562e8deda090 - sys::backtrace::tracing::imp::write::haa19c02b4de52f3bG0t
   2:     0x562e8dedc535 - panicking::log_panic::_<closure>::closure.41218
   3:     0x562e8dedbfb0 - panicking::log_panic::h527fe484e9de8fe1W7x
   4:     0x562e8decd453 - sys_common::unwind::begin_unwind_inner::h51f64b1a34c60827fTs
   5:     0x562e8decdb08 - sys_common::unwind::begin_unwind_fmt::h0845853a1913f45blSs
   6:     0x562e8ded96f1 - rust_begin_unwind
   7:     0x562e8df0898f - panicking::panic_fmt::h3967afc085fe8067LFK
   8:     0x562e8dd552a1 - result::_<impl>::expect::expect::h14909738735884939944
                        at ../src/libcore/macros.rs:29
   9:     0x562e8dd393af - bridge::_<impl>::handle_client::h4c3beb9fd3688262Dec
                        at src/bridge.rs:378
  10:     0x562e8dd38b82 - bridge::_<impl>::ready::hbc9d7d5120ba7167rKb
                        at src/bridge.rs:50
  11:     0x562e8dd47a13 - event_loop::_<impl>::io_event::io_event::h16631942979517961819
                        at /home/jonathan/.cargo/registry/src/github.com-88ac128001ac3a9a/mio-0.5.0/src/event_loop.rs:343
  12:     0x562e8dd47949 - event_loop::_<impl>::io_process::io_process::h3603654275074776935
                        at /home/jonathan/.cargo/registry/src/github.com-88ac128001ac3a9a/mio-0.5.0/src/event_loop.rs:335
  13:     0x562e8dd47180 - event_loop::_<impl>::run_once::run_once::h3489195311041105944
                        at /home/jonathan/.cargo/registry/src/github.com-88ac128001ac3a9a/mio-0.5.0/src/event_loop.rs:298
  14:     0x562e8dd46b0c - event_loop::_<impl>::run::run::h11559222182195999125
                        at /home/jonathan/.cargo/registry/src/github.com-88ac128001ac3a9a/mio-0.5.0/src/event_loop.rs:247
  15:     0x562e8dcf3956 - bridge::_<impl>::run::h450c39ab45a6496cW7b
                        at src/bridge.rs:276
  16:     0x562e8dcf3405 - _<impl>::ready::_<closure>::closure.14307
                        at src/main.rs:56
  17:     0x562e8dcf2e43 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.14260
                        at ../src/libstd/thread/mod.rs:274
  18:     0x562e8dcf2db8 - sys_common::unwind::try::try_fn::try_fn::h261978716724135801
                        at ../src/libstd/sys/common/unwind/mod.rs:163
  19:     0x562e8ded9538 - __rust_try
  20:     0x562e8ded648b - sys_common::unwind::try::inner_try::h771fec597ec8f35cNPs
  21:     0x562e8dcf2cf5 - sys_common::unwind::try::try::h16901009832689950734
                        at ../src/libstd/sys/common/unwind/mod.rs:133
  22:     0x562e8dcf2b3b - std::thread::_<impl>::spawn::_<closure>::closure.14235
                        at ../src/libstd/thread/mod.rs:274
  23:     0x562e8dcf3697 - boxed::_<impl>::call_box::call_box::h4900206345153519334
  24:     0x562e8dedb083 - sys::thread::_<impl>::new::thread_start::haf749b76474da6b089w
  25:     0x7f3cc06af181 - start_thread
  26:     0x7f3cc0ec947c - __clone
  27:                0x0 - <unknown>
```

**Comment by tdfischer** [comment]
Thanks for the crash report!

I'm wondering what version of PTO you're using. This new 0.3.0 release just made today should have some more verbose output.

If I run PTO locally against terracrypt.net, I get:

```
+[src](master)[tdfischer@singularity pto]$ cargo run -- terracrypt.net
     Running `target/debug/pto terracrypt.net`
INFO:pto: Starting PTO 0.2.0
WARN:pto: SSL IS DISABLED!! IRC LOGINS ARE IN THE CLEAR AND UNENCRYPTED
INFO:pto: Listening on 127.0.0.1:8001
INFO:pto: Using matrix URL at https://terracrypt.net:8448/_matrix
thread '<unnamed>' panicked at 'Could not login!: BadStatus(Forbidden)', ../src/libcore/result.rs:760
```

There's been some improvements to the URL heuristics that should fix a lot of configurations but no heuristic is perfect. What is the matrix URL you're expecting PTO to figure out?
